services:
  {{APP}}:
    image: $IMAGE
    container_name: $CONTAINER_NAME
    pull_policy: always
    env_file:
      - .env
      - .service.env
      - .auth
    volumes:
      - ./.auth:/config/.auth
    restart: unless-stopped
    ports:
      - ${PORT}:80
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 150M
    logging:
      driver: "json-file"
      options:
        max-size: "48m"
        max-file: "3"
        tag: "{{.Name}}"

